# -*- mode: ruby -*-
# vi: set ft=ruby :



# iSCSI TARGET MACHINE CONFIGURATION

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/xenial64"
  # config.vm.provision :shell, path: "Initiator_setup.sh"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.1.150"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
     vb.name = "initiator"

   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.

  # update, enable the initiator
  config.vm.provision "shell", inline: <<-SHELL
     echo Initiator set up:
     sudo sed -i 's/127.0.0.1 localhost/127.0.0.1 localhost localhost.localdomain ubuntu-xenial/' /etc/hosts
     sudo apt-get --yes --force-yes update
     sudo apt-get --yes --force-yes upgrade
     route add default gw 192.168.1.1
     sudo apt-get --yes --force-yes install open-iscsi
     echo changing archives
     sudo sed -i 's/node.startup = manual/# node.startup = manual/' /etc/iscsi/iscsid.conf
     sudo sed -i 's/# node.startup = automatic/node.startup = automatic/' /etc/iscsi/iscsid.conf
     sudo sed -i 's/# By default this script does nothing./sudo ifconfig enp0s8 mtu 5000 || exit 1/' /etc/rc.local
     cd /
     sudo wget https://raw.githubusercontent.com/illinoistech-itm/pykkon/Vagrant-Config/Shellscript/iSCSI-initiator-setup.sh
     sudo chmod 755 iSCSI-initiator-setup.sh

     sudo wget https://raw.githubusercontent.com/illinoistech-itm/pykkon/Vagrant-Config/Shellscript/iSCSI-initiator-logout.sh
     sudo chmod 755 iSCSI-initiator-logout.sh

  SHELL
end
